version: '3.1'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
        - '3306:3306'
    volumes:
        - mysql_data:/var/lib/mysql
volumes:
  mysql_data: